### ISSUE TITLE
关于 net-r8125-9.011.00-10.vib 原始出处

### ISSUE THREAD

**Issue by shing-lee** [itiligent/ESXi-Custom-ISO#1]
感谢您的分享的脚本
此 vib 文件的原始出处是：https://github.com/mcr-ksh/r8125-esxi
并且还发行 Offline Bundle zip 包，可以直接封装到 iso 文件中

**Comment by itiligent** [comment]
Kindly note that your link to the original source is already credited in the actual script file. Thanks for sharing your code!
