### ISSUE TITLE
support 8.0.3

### ISSUE THREAD

**Issue by alsyundawy** [itiligent/ESXi-Custom-ISO#11]
support 8.0.3

**Comment by itiligent** [comment]
The VMware community Fling currently only supports up to 8.02, and on 8.03 it appears to break.

See here: 
https://community.broadcom.com/vmware-code/discussion/lastest-for-u3-usb-network-native-driver-for-esxi-not-work#bm3ba19dfe-5fef-4d8f-888a-67696903b9d0

As a workaround, if you need USB NIC support you can stay with 8.02, or if you dont need USB NIC support, comment out the following script lines and it will build fine. 
`$usbFling = "ESXi80U2-VMKUSB-NIC-FLING-67561870-component-22416446.zip"`
and 
`Add-EsxSoftwarePackage -ImageProfile $newProfile -SoftwarePackage "vmkusb-nic-fling" -Force`

I'll update the script as and when an updated driver Fling is released.

**Comment by itiligent** [comment]
I just noticed there is an updated Fling for 8.0U3, so I've addeded this and its now working for 8.0U3. See script comments for Broadcom Fling download links to either upgrade in future or build lower versions .
