### ISSUE TITLE
VMware ESXi With macOS Unlocker & OEM BIOS

### ISSUE THREAD

**Issue by alsyundawy** [itiligent/ESXi-Custom-ISO#12]
can you support

VMware ESXi With macOS Unlocker & OEM BIOS For All Version

like https://sysin.org/categories/#VMware

**Comment by itiligent** [comment]
Hi, if there is a vib to include then potentially yes (at least for esxi 6.7) If you have a suggestion to add, please take some time to provide more info as in what is the current problem? what outcome you want to achieve as that link does not direct me anywhere very helpful to understand what is the issue.  Please remember this is free software.

**Comment by alsyundawy** [comment]
for 6.7 & 7
https://github.com/netgc/esxi-unlocker

For 8
https://github.com/netgc/esxi-unlocker-4

**Comment by itiligent** [comment]
After taking a look, this code actually patches the vmx, vmx-debug and vmx-stats executables of ESXI's virtual System Management Controller, and patching must be done repeatably with each esxi upgrade, meaning there is no point baking this into any build - plus as this is an edge use case its not something I want to introduce into this repo for many reasons. 

You could expermient by building your ESXI with this repo, installing it, and then patching all the necessary executables - then you could then modify the ISO to include those patched executables perhaps?
