### ISSUE TITLE
Python 2.7.17 installer

### ISSUE THREAD

**Issue by alsyundawy** [itiligent/ESXi-Custom-ISO#14]
https://github.com/adang1345/PythonWindows/tree/master/3.7.17

**Comment by itiligent** [comment]
A  zero effort post with no clear requirement or context , so unfotunatlely I must close. 

To rasie issues you must be prepeared to take the time explain the issue or requirement,  detail the steps taken so far, and also include all necessary referneces or backgound. Please remember this is free software, and respectful collaborative effort is what builds a community.
