### ISSUE TITLE
esx-ui 2.18

### ISSUE THREAD

**Issue by alsyundawy** [itiligent/ESXi-Custom-ISO#16]
https://hostupdate.vmware.com/software/VUM/PRODUCTION/main/esx/vmw/vib20/esx-ui/VMware_bootbank_esx-ui_2.18.0-23593406.vib

**Comment by itiligent** [comment]
I've politely asked you several times in other issues about zero effort posts and to please make an effort to explain what you have linked or what your issue may be.  (This link is not the 20243001 update previously mentioned in another case).  An answer without a question you will appreciate has no value, and is just a puzzle without any context. 

It would be a helpful courtesy for you to explain yourself and provide the details of the issue you are experiencing, or the details around what you are asking. Without this I must close.

**Comment by itiligent** [comment]
closing due to no info provided
