### ISSUE TITLE
ESXi 6.7 dowloaded zip seems to be missing components ...failing esx image validation

### ISSUE THREAD

**Issue by PJMead** [itiligent/ESXi-Custom-ISO#18]
I too cannot get this custom build to work! below is a simple script that 
1. Clears the depot
2. adds the downloaded (not vmware version) file ESXi670-202403001.zip
3.  adds it to the depot
4.  queries the depot for image profiles
5.  Exports the image to a zip file.

either your base software is different OR your base zip file is different to mine

PS H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX> ls

    Directory: H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        01/08/2024     14:16           6460 Build_Custom_ESX_6.7.ps1
-a----        01/08/2024     15:28      330546005 ESXi-6.7.0-20240304001-standard.zip
-a----        01/08/2024     13:02      330539208 ESXi670-202403001.zip
-a----        01/08/2024     11:15         452722 ESXi670-VMKUSB-NIC-FLING-39203948-offline_bundle-16780994.zip
-a----        01/08/2024     11:15         106827 net-igb-5.3.2-99-offline_bundle.zip
-a----        01/08/2024     11:15        1131668 net55-r8168-8.045a-napi-offline_bundle.zip
-a----        01/08/2024     11:15          89423 nvme-community-driver_1.0.1.0-1vmw.670.0.0.8169922-offline_bundle-17658145.zip
-a----        01/08/2024     15:23          25333 vghetto-ghettoVCB-offline-bundle-7x.zip

PS H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX> get-esxsoftwaredepot | Remove-EsxSoftwareDepot
PS H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX> get-esxsoftwaredepot
PS H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX> get-powercliversion

PowerCLI Version
----------------
   VMware.PowerCLI 13.0.0 build 20829139
---------------
Component Versions
---------------
   VMware Common PowerCLI Component 13.3 build 24145081
   VMware Cis Core PowerCLI Component PowerCLI Component 13.3 build 24145081
   VMware VimAutomation VICore Commands PowerCLI Component PowerCLI Component 13.3 build 24145081
   VMware Image Builder PowerCLI Component PowerCLI Component 13.3 build 24145081

PS H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX> #
PS H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX> #
PS H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX> add-esxsoftwaredepot "ESXi670-202403001.zip"

Depot Url
---------
zip:H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX\ESXi670-202403001.zip?index.xml

PS H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX> get-esxsoftwaredepot

Depot Url
---------
zip:H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX\ESXi670-202403001.zip?index.xml

PS H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX> #
PS H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX> get-esximageprofile

Name                           Vendor          Last Modified   Acceptance Level
----                           ------          -------------   ----------------
ESXi-6.7.0-20240304001-stan... VMware, Inc.    13/02/2024 1... PartnerSupported
ESXi-6.7.0-20240304001-no-t... VMware, Inc.    13/02/2024 1... PartnerSupported

PS H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX> #
PS H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX> #
PS H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX> Export-ESXImageProfile -ImageProfile "ESXi-6.7.0-20240304001-standard" -ExportToBundle -filepath "ESXi-6.7.0-20240304001-test.zip"
**WARNING: The image profile fails validation.  The ISO / Offline Bundle will still be generated but may contain errors and may not boot or be functional.  Errors:
WARNING:   Profile ESXi-6.7.0-20240304001-standard is missing component(s)
ESXi,Intel-Volume-Mgmt-Device,Intel-ne1000,Mellanox-nmlx5,VMware-NVMeoF-RDMA,VMware-ahci,VMware-iser,VMware-nvme-pcie-plugin,VMware-nvme-plugin,VMware-nvmxnet3,VMware-nvmxnet3-ens,VMware-pvscsi,VMware-vmkata,VM
ware-vmkusb,esx-update which are necesary and removing them is prohibited. Please ensure that these components, which are part of the ESXi release version 6.7.0-3.193.23084122, are fully installed or overridden
 without partial VIB replacement or removal.**
 
PS H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX> ls

    Directory: H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        01/08/2024     14:16           6460 Build_Custom_ESX_6.7.ps1
-a----        01/08/2024     15:28      330546005 ESXi-6.7.0-20240304001-standard.zip
-a----        01/08/2024     15:46      330546013 ESXi-6.7.0-20240304001-test.zip
-a----        01/08/2024     13:02      330539208 ESXi670-202403001.zip
-a----        01/08/2024     11:15         452722 ESXi670-VMKUSB-NIC-FLING-39203948-offline_bundle-16780994.zip
-a----        01/08/2024     11:15         106827 net-igb-5.3.2-99-offline_bundle.zip
-a----        01/08/2024     11:15        1131668 net55-r8168-8.045a-napi-offline_bundle.zip
-a----        01/08/2024     11:15          89423 nvme-community-driver_1.0.1.0-1vmw.670.0.0.8169922-offline_bundle-17658145.zip
-a----        01/08/2024     15:23          25333 vghetto-ghettoVCB-offline-bundle-7x.zip

PS H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX>

**Comment by PJMead** [comment]
the ESXi zip file was downloaded from here:
https://mirror.mahanserver.net/VMware/ESXI/6.7.0/ESXi670-202403001.zip

**Comment by itiligent** [comment]
Unfotunately I am not able to make anything out of what you have submitted. 
What script are you talking about ?- there is no "simple script" contained in the above, just some garbled output.If you are submitting code then please format it with ``` to make it display correclty in github.
 
You appear to be trying to use some sort of locally stored ESXI 6.7 source downloaded from a non VMware location (risky) and you are running the script in some way to try to make this into an ISO.  You dont seem to be using this repo for how it was intended or you have modified it in some way. If that is the case I am not able to help you there.  Also I caution you about random online vmware sources as these are often tampered with - hence the "validation" errors which are possibly trying to tell you something.  

If you run the 6.7 script AS IS  it will build thr latest 2024 version of esxi 6.7 **from official vmware source** with all the extra drivers and you will also be able to validate all the files and sources within it with a little bit of SHA checking.

Here is the output you will I see (I  ran it again now)........
```PS C:\Users\David\Desktop\testing> .\esxi6.7.ps1
Retrieving ESXi 6.7 installation bundles to choose from, this may take a while...


Depot Url
---------
zip:C:\Users\David\Desktop\testing\ESXi670-202403001.zip?index.xml
https://hostupdate.vmware.com/software/VUM/PRODUCTION/main/vmw-depot-index.xml
1

1. ESXi-6.7.0-20240304001-standard
2. ESXi-6.7.0-20221004001-standard
3. ESXi-6.7.0-20221001001s-standard
4. ESXi-6.7.0-20220704001-standard
5. ESXi-6.7.0-20220604001-standard
6. ESXi-6.7.0-20220601001s-standard
7. ESXi-6.7.0-20220104001-standard
8. ESXi-6.7.0-20211104001-standard
9. ESXi-6.7.0-20211101001s-standard
10. ESXi-6.7.0-20210304001-standard
11. ESXi-6.7.0-20210301001s-standard
12. ESXi-6.7.0-20210204001-standard
13. ESXi-6.7.0-20201104001-standard
14. ESXi-6.7.0-20201103001-standard
15. ESXi-6.7.0-20201101001s-standard
16. ESXi-6.7.0-20201004001-standard
17. ESXi-6.7.0-20200804001-standard
18. ESXi-6.7.0-20200801001s-standard
19. ESXi-6.7.0-20200604001-standard
20. ESXi-6.7.0-20200404001-standard
21. ESXi-6.7.0-20200403001-standard
22. ESXi-6.7.0-20200401001s-standard
23. ESXi-6.7.0-20191204001-standard
24. ESXi-6.7.0-20191201001s-standard
25. ESXi-6.7.0-20191104001-standard
26. ESXi-6.7.0-20190802001-standard
27. ESXi-6.7.0-20190801001s-standard
28. ESXi-6.7.0-20190604001-standard
29. ESXi-6.7.0-20190504001-standard
30. ESXi-6.7.0-20190404001-standard
31. ESXi-6.7.0-20190402001-standard
32. ESXi-6.7.0-20190401001s-standard
33. ESXi-6.7.0-20190304001-standard
34. ESXi-6.7.0-20190104001-standard
35. ESXi-6.7.0-20181104001-standard
36. ESXi-6.7.0-20181004001-standard
37. ESXi-6.7.0-20181002001-standard
38. ESXi-6.7.0-20181001001s-standard
39. ESXi-6.7.0-20180804001-standard
40. ESXi-6.7.0-20180704001-standard
41. ESXi-6.7.0-20180604001-standard
42. ESXi-6.7.0-8169922-standard
Select an ESXi image profile (1-42): 1

Downloading ESXi-6.7.0-20240304001-standard and exporting to an image bundle


Finished retrieving latest ESXi 6.7 bundle


Adding extra packages to the local depot

zip:C:\Users\David\Desktop\testing\ESXi-6.7.0-20240304001-standard.zip?inde...
zip:C:\Users\David\Desktop\testing\nvme-community-driver_1.0.1.0-1vmw.670.0...
zip:C:\Users\David\Desktop\testing\ESXi670-VMKUSB-NIC-FLING-39203948-offlin...
zip:C:\Users\David\Desktop\testing\net55-r8168-8.045a-napi-offline_bundle.z...
zip:C:\Users\David\Desktop\testing\net-igb-5.3.2-99-offline_bundle.zip?inde...
zip:C:\Users\David\Desktop\testing\vghetto-ghettoVCB-offline-bundle-7x.zip?...

Creating a custom profile


Name            : ESXi-6.7.0-20240304001-nvme-usbnic-zimanic
Vendor          : Itiligent
Author          :
Description     : Updates ESXi 6.7 Image Profile-ESXi-6.7.0-20240304001-standard
CreationTime    : 13/02/2024 12:10:26 PM
ModifiedTime    : 2/08/2024 4:37:58 AM
ReadOnly        : False
VibList         : {net-igb 5.0.5.1.1-5vmw.670.0.0.8169922, sata-sata-promise 2.12-3vmw.670.0.0.8169922, shim-libfcoe-9-2-1-0
                  6.7.0-0.0.8169922, lsu-lsi-lsi-mr3-plugin 1.0.0-13vmw.670.1.28.10302608...}
ReservedVibList :
AcceptanceLevel : CommunitySupported
Guid            : 14cbe02f-ec0d-4bf4-9987-6dafdaefa38f
Rules           :
StatelessReady  : True


Injecting extra packages into the custom profile


Name            : ESXi-6.7.0-20240304001-nvme-usbnic-zimanic
Vendor          : Itiligent
Author          :
Description     : Updates ESXi 6.7 Image Profile-ESXi-6.7.0-20240304001-standard
CreationTime    : 13/02/2024 12:10:26 PM
ModifiedTime    : 2/08/2024 4:37:58 AM
ReadOnly        : False
VibList         : {net-igb 5.0.5.1.1-5vmw.670.0.0.8169922, sata-sata-promise 2.12-3vmw.670.0.0.8169922, shim-libfcoe-9-2-1-0
                  6.7.0-0.0.8169922, lsu-lsi-lsi-mr3-plugin 1.0.0-13vmw.670.1.28.10302608...}
ReservedVibList :
AcceptanceLevel : CommunitySupported
Guid            : 14cbe02f-ec0d-4bf4-9987-6dafdaefa38f
Rules           :
StatelessReady  : True


Name            : ESXi-6.7.0-20240304001-nvme-usbnic-zimanic
Vendor          : Itiligent
Author          :
Description     : Updates ESXi 6.7 Image Profile-ESXi-6.7.0-20240304001-standard
CreationTime    : 13/02/2024 12:10:26 PM
ModifiedTime    : 2/08/2024 4:37:59 AM
ReadOnly        : False
VibList         : {net-igb 5.0.5.1.1-5vmw.670.0.0.8169922, sata-sata-promise 2.12-3vmw.670.0.0.8169922, shim-libfcoe-9-2-1-0
                  6.7.0-0.0.8169922, lsu-lsi-lsi-mr3-plugin 1.0.0-13vmw.670.1.28.10302608...}
ReservedVibList :
AcceptanceLevel : CommunitySupported
Guid            : 14cbe02f-ec0d-4bf4-9987-6dafdaefa38f
Rules           :
StatelessReady  : True


Name            : ESXi-6.7.0-20240304001-nvme-usbnic-zimanic
Vendor          : Itiligent
Author          :
Description     : Updates ESXi 6.7 Image Profile-ESXi-6.7.0-20240304001-standard
CreationTime    : 13/02/2024 12:10:26 PM
ModifiedTime    : 2/08/2024 4:37:59 AM
ReadOnly        : False
VibList         : {net-igb 5.0.5.1.1-5vmw.670.0.0.8169922, sata-sata-promise 2.12-3vmw.670.0.0.8169922, shim-libfcoe-9-2-1-0
                  6.7.0-0.0.8169922, lsu-lsi-lsi-mr3-plugin 1.0.0-13vmw.670.1.28.10302608...}
ReservedVibList :
AcceptanceLevel : CommunitySupported
Guid            : 14cbe02f-ec0d-4bf4-9987-6dafdaefa38f
Rules           :
StatelessReady  : True


Name            : ESXi-6.7.0-20240304001-nvme-usbnic-zimanic
Vendor          : Itiligent
Author          :
Description     : Updates ESXi 6.7 Image Profile-ESXi-6.7.0-20240304001-standard
CreationTime    : 13/02/2024 12:10:26 PM
ModifiedTime    : 2/08/2024 4:37:59 AM
ReadOnly        : False
VibList         : {sata-sata-promise 2.12-3vmw.670.0.0.8169922, shim-libfcoe-9-2-1-0 6.7.0-0.0.8169922, lsu-lsi-lsi-mr3-plugin
                  1.0.0-13vmw.670.1.28.10302608, sata-sata-sil24 1.1-1vmw.670.0.0.8169922...}
ReservedVibList :
AcceptanceLevel : CommunitySupported
Guid            : 14cbe02f-ec0d-4bf4-9987-6dafdaefa38f
Rules           :
StatelessReady  : True


Name            : ESXi-6.7.0-20240304001-nvme-usbnic-zimanic
Vendor          : Itiligent
Author          :
Description     : Updates ESXi 6.7 Image Profile-ESXi-6.7.0-20240304001-standard
CreationTime    : 13/02/2024 12:10:26 PM
ModifiedTime    : 2/08/2024 4:37:59 AM
ReadOnly        : False
VibList         : {sata-sata-promise 2.12-3vmw.670.0.0.8169922, shim-libfcoe-9-2-1-0 6.7.0-0.0.8169922, lsu-lsi-lsi-mr3-plugin
                  1.0.0-13vmw.670.1.28.10302608, sata-sata-sil24 1.1-1vmw.670.0.0.8169922...}
ReservedVibList :
AcceptanceLevel : CommunitySupported
Guid            : 14cbe02f-ec0d-4bf4-9987-6dafdaefa38f
Rules           :
StatelessReady  : True


Exporting the custom profile to an ISO...


Build complete
```

**Comment by PJMead** [comment]
A touch of arrogance or impatience creeping in there!
here is my simple test script, to avoid running the whole process , to test the depot zip image creation.

#
# NEEDS PYTHON version greater than 3.7.1  
#
clear
#
#
Set-ExecutionPolicy -ExecutionPolicy remotesigned -scope CurrentUser
Import-Module VMware.ImageBuilder
cd H:\NAS_01_Backup_20240726_1447\VmWARE\Build_ESX
get-powercliversion
python -c "import sys; print(sys.version)"
ls
get-esxsoftwaredepot | Remove-EsxSoftwareDepot
get-esxsoftwaredepot
get-powercliversion
add-esxsoftwaredepot "ESXi670-202403001.zip"
get-esxsoftwaredepot
get-esximageprofile
Export-ESXImageProfile -ImageProfile "ESXi-6.7.0-20240304001-standard" -ExportToBundle -filepath "ESXi-6.7.0-20240304001-test.zip" -force
ls

and this is the warning I warning I get from the export:

Export-ESXImageProfile -ImageProfile "ESXi-6.7.0-20240304001-standard" -ExportToBundle -filepath "ESXi-6.7.0-20240304001-test.zip" -force
WARNING: The image profile fails validation.  The ISO / Offline Bundle will still be generated but may contain errors and may not boot or be functional.  Errors:
WARNING:   Profile ESXi-6.7.0-20240304001-standard is missing component(s)
ESXi,Intel-Volume-Mgmt-Device,Intel-ne1000,Mellanox-nmlx5,VMware-NVMeoF-RDMA,VMware-ahci,VMware-iser,VMware-nvme-pcie-plugin,VMware-nvme-plugin,VMware-nvmxnet3,VMware-nvmxnet3-ens,VMware-pvscsi,VMware-vmkata,VM
ware-vmkusb,esx-update which are necesary and removing them is prohibited. Please ensure that these components, which are part of the ESXi release version 6.7.0-3.193.23084122, are fully installed or overridden
 without partial VIB replacement or removal.

simple enough for you?

I appreciate the script works for you , try running the above, either my zip file is faulty (unlikely) or your environment is different to mine!

I am running 
Windows 10, 
Powercli 13.0.0 build 20829139, 
Python 3.7.9

**Comment by PJMead** [comment]
I am doing this exercise because I need to add some OCZ SSD drivers to the ESXi build , I have done this in the past (more than 10 years ago) and can't remember how! I think the ESXi 6.0.0 had a break in the install to add external drivers.

any idea how to convert the drivers I have on a CD to a depot format?

**Comment by PJMead** [comment]
BTW I get exactly the same warning using the 'official' vmware depot.....

 **Export-ESXImageProfile -ImageProfile "**ESXi-6.7.0-20221004001-standard**" -ExportToBundle -filepath "ESXi-6.7.0-20221004001-VM-test.zip" -force**
#
WARNING: The image profile fails validation.  The ISO / Offline Bundle will still be generated but may contain errors and may not boot or be functional.  Errors:
WARNING:   Profile ESXi-6.7.0-20221004001-standard is missing component(s)
ESXi,Intel-Volume-Mgmt-Device,Intel-ne1000,Mellanox-nmlx5,VMware-NVMeoF-RDMA,VMware-ahci,VMware-iser,VMware-nvme-pcie-plugin,VMware-nvme-plugin,VMware-nvmxnet3,VMware-nvmxnet3-ens,VMware-pvscsi,VMware-vmkata,VM
ware-vmkusb,esx-update which are necesary and removing them is prohibited. Please ensure that these components, which are part of the ESXi release version 6.7.0-3.189.20497097, are fully installed or overridden
 without partial VIB replacement or removal.
#

**Comment by itiligent** [comment]
I welcome you to raise an issue with code in THIS repo so I might improve it.  

I am sorry you believe I was not helpful, but you may have missed that Github is a actually forum for collaborating and supporting published code in THIS  repo, so this is the source of confusion (as this is the only topic that is expected).  
In this context you may better see how my questions were laser focued on trying to figure the relevance your question has to THIS repo. 

I actually spent a good deal of time on this for you,  but without equivalent time taken to ariticaulte your ask,  I dont think you've been very fair on me.  Please remeber you are asking for help with your own homework, and I've tried to help you in the context of Github with the info I have in foront of me.  Reddit might offer you what you are looking for.
