### ISSUE TITLE
esxi8 custom iso show many WARNING

### ISSUE THREAD

**Issue by heroes1412** [itiligent/ESXi-Custom-ISO#2]
VIBs: {'VMware_bootbank_esx-base_8.0.2-0.0.22380479', 'VMware_bootbank_esxio-base_8.0.2-0.0.22380479'}
WARNING:   File path of '/lib64/python3.8/site-packages/pyMo/vim/__init__.pyc' is claimed by multiple non-overlay VIBs:
 {'VMware_bootbank_esx-base_8.0.2-0.0.22380479', 'VMware_bootbank_esxio-base_8.0.2-0.0.22380479'}
WARNING:   File path of '/etc/vmware/secpolicy/domains/esxcfgInfoCgiDom' is claimed by multiple non-overlay VIBs:
{'VMware_bootbank_esx-base_8.0.2-0.0.22380479', 'VMware_bootbank_esxio-base_8.0.2-0.0.22380479'}
WARNING:   File path of '/lib64/python3.8/idlelib/idle_test/test_calltip_w.pyc' is claimed by multiple non-overlay
VIBs: {'VMware_bootbank_esx-base_8.0.2-0.0.22380479', 'VMware_bootbank_esxio-base_8.0.2-0.0.22380479'}
WARNING:   File path of '/lib64/python3.8/asyncio/base_events.pyc' is claimed by multiple non-overlay VIBs:
{'VMware_bootbank_esx-base_8.0.2-0.0.22380479', 'VMware_bootbank_esxio-base_8.0.2-0.0.22380479'}
WARNING:   File path of '/lib64/python3.8/email/encoders.pyc' is claimed by multiple non-overlay VIBs:
{'VMware_bootbank_esx-base_8.0.2-0.0.22380479', 'VMware_bootbank_esxio-base_8.0.2-0.0.22380479'}
WARNING:   File path of '/etc/vmware/secpolicy/domains/healthdDom' is claimed by multiple non-overlay VIBs:
{'VMware_bootbank_esx-base_8.0.2-0.0.22380479', 'VMware_bootbank_esxio-base_8.0.2-0.0.22380479'}
WARNING:   File path of '/lib64/python3.8/gevent/subprocess.py' is claimed by multiple non-overlay VIBs:
{'VMware_bootbank_esx-base_8.0.2-0.0.22380479', 'VMware_bootbank_esxio-base_8.0.2-0.0.22380479'}
WARNING:   File path of '/etc/init.d/vvold' is claimed by multiple non-overlay VIBs:
{'VMware_bootbank_esx-base_8.0.2-0.0.22380479', 'VMware_bootbank_esxio-base_8.0.2-0.0.22380479'}
WARNING:   File path of '/etc/vmware/default.map.d/vmknvme.map' is claimed by multiple non-overlay VIBs:
{'VMware_bootbank_native-misc-drivers_8.0.2-0.0.22380479',
'VMware_bootbank_native-misc-drivers-esxio_8.0.2-0.0.22380479'}
WARNING:   File path of '/etc/vmware/hostd/tagExtractor.xml' is claimed by multiple non-overlay VIBs:
{'VMware_bootbank_esx-base_8.0.2-0.0.22380479', 'VMware_bootbank_esxio-base_8.0.2-0.0.22380479'}
WARNING:   File path of '/usr/lib/vmware/likewise/share/config/lsassd.reg' is claimed by multiple non-overlay VIBs:
{'VMware_bootbank_esx-base_8.0.2-0.0.22380479', 'VMware_bootbank_esxio-base_8.0.2-0.0.22380479

**Comment by heroes1412** [comment]
No iso v8 is created.

New-EsxImageProfile : File path of '/usr/lib/vmware/vm-support/bin/partedUtil.sh' is claimed by multiple non-overlay
VIBs: {'VMware_bootbank_esx-base_8.0.2-0.0.22380479', 'VMware_bootbank_esxio-base_8.0.2-0.0.22380479'}
At C:\Users\hoangtv\Downloads\ESXi-Custom-ISO-main\esxi8-nvme-usbnic.ps1:66 char:15
+ ... ewProfile = New-EsxImageProfile -CloneProfile $imageProfile -name $ne ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (VMware.ImageBuilder.Types.ImageProfile:ImageProfile) [New-EsxImageProfile]
   , Exception
    + FullyQualifiedErrorId : EsxImageProfileValidationError,VMware.ImageBuilder.Commands.NewImageProfile

New-EsxImageProfile : File path of '/usr/lib/vmware/hostd/hmo/imageConfigManager.py' is claimed by multiple
non-overlay VIBs: {'VMware_bootbank_esx-base_8.0.2-0.0.22380479', 'VMware_bootbank_esxio-base_8.0.2-0.0.22380479'}
At C:\Users\hoangtv\Downloads\ESXi-Custom-ISO-main\esxi8-nvme-usbnic.ps1:66 char:15
+ ... ewProfile = New-EsxImageProfile -CloneProfile $imageProfile -name $ne ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (VMware.ImageBuilder.Types.ImageProfile:ImageProfile) [New-EsxImageProfile]
   , Exception
    + FullyQualifiedErrorId : EsxImageProfileValidationError,VMware.ImageBuilder.Commands.NewImageProfile

**Comment by itiligent** [comment]
The script works perfectly. Please check your enviroment and follw the readme.  The errors looks like you have the wrong python version installed. It you have a lot of libraries or a mixed build environment PowerCLI can be painful. I just ran it now and here is the result using  VMware.PowerCLI 13.1.0 build 21624340

`PS C:\Users\test\Desktop\8> .\esxi8-nvme-usbnic.ps1                                                                  
Retrieving a list of ESXi 8 installation bundles to choose from, this may take a while...


Depot Url
https://hostupdate.vmware.com/software/VUM/PRODUCTION/main/vmw-depot-index.xml
1. ESXi-8.0U2-22380479-standard
2. ESXi-8.0U1sc-22082334-standard
3. ESXi-8.0U1c-22088125-standard
4. ESXi-8.0U1a-21813344-standard
5. ESXi-8.0U1-21495797-standard
6. ESXi-8.0sb-21203431-standard
7. ESXi-8.0c-21493926-standard
8. ESXi-8.0b-21203435-standard
9. ESXi-8.0a-20842819-standard
10. ESXi-8.0.0-20513097-standard
Select an ESXi image profile (1-10): 1

Downloading ESXi-8.0U2-22380479-standard


Finished retrieving ESXi-8.0U2-22380479-standard


Adding extra packages to the local depot

zip:C:\Users\David\Desktop\8\ESXi-8.0U2-22380479-standard.zip?index.xml
zip:C:\Users\David\Desktop\8\nvme-community-driver_1.0.1.0-3vmw.700.1.0.158...
zip:C:\Users\David\Desktop\8\ESXi80U2-VMKUSB-NIC-FLING-67561870-component-2...
zip:C:\Users\David\Desktop\8\vghetto-ghettoVCB-offline-bundle.zip?index.xml

Creating a custom profile


Name            : ESXi-8.0U2-22380479-nvme-usbnic
Vendor          : Itiligent
Author          :
Description     : The general availability release of VMware ESXi Server 8.0U2 brings whole new levels of
                  virtualization performance to datacenters and enterprises.
CreationTime    : 21/09/2023 12:00:00 AM
ModifiedTime    : 6/12/2023 9:02:31 PM
ReadOnly        : False
VibList         : {esxio-base 8.0.2-0.0.22380479, loadesx 8.0.2-0.0.22380479, cndi-igc
                  1.2.10.0-1vmw.802.0.0.22380479, vmkata 0.1-1vmw.802.0.0.22380479...}
ReservedVibList :
AcceptanceLevel : CommunitySupported
Guid            : bbda27a4-0902-4a49-b634-4dc316b49812
Rules           :
StatelessReady  : True


Injecting extra packages into the custom profile


Name            : ESXi-8.0U2-22380479-nvme-usbnic
Vendor          : Itiligent
Author          :
Description     : The general availability release of VMware ESXi Server 8.0U2 brings whole new levels of
                  virtualization performance to datacenters and enterprises.
CreationTime    : 21/09/2023 12:00:00 AM
ModifiedTime    : 6/12/2023 9:02:31 PM
ReadOnly        : False
VibList         : {esxio-base 8.0.2-0.0.22380479, loadesx 8.0.2-0.0.22380479, cndi-igc
                  1.2.10.0-1vmw.802.0.0.22380479, vmkata 0.1-1vmw.802.0.0.22380479...}
ReservedVibList :
AcceptanceLevel : CommunitySupported
Guid            : bbda27a4-0902-4a49-b634-4dc316b49812
Rules           :
StatelessReady  : True


Name            : ESXi-8.0U2-22380479-nvme-usbnic
Vendor          : Itiligent
Author          :
Description     : The general availability release of VMware ESXi Server 8.0U2 brings whole new levels of
                  virtualization performance to datacenters and enterprises.
CreationTime    : 21/09/2023 12:00:00 AM
ModifiedTime    : 6/12/2023 9:02:31 PM
ReadOnly        : False
VibList         : {esxio-base 8.0.2-0.0.22380479, loadesx 8.0.2-0.0.22380479, cndi-igc
                  1.2.10.0-1vmw.802.0.0.22380479, vmkata 0.1-1vmw.802.0.0.22380479...}
ReservedVibList :
AcceptanceLevel : CommunitySupported
Guid            : bbda27a4-0902-4a49-b634-4dc316b49812
Rules           :
StatelessReady  : True


Name            : ESXi-8.0U2-22380479-nvme-usbnic
Vendor          : Itiligent
Author          :
Description     : The general availability release of VMware ESXi Server 8.0U2 brings whole new levels of
                  virtualization performance to datacenters and enterprises.
CreationTime    : 21/09/2023 12:00:00 AM
ModifiedTime    : 6/12/2023 9:02:31 PM
ReadOnly        : False
VibList         : {esxio-base 8.0.2-0.0.22380479, loadesx 8.0.2-0.0.22380479, cndi-igc
                  1.2.10.0-1vmw.802.0.0.22380479, vmkata 0.1-1vmw.802.0.0.22380479...}
ReservedVibList :
AcceptanceLevel : CommunitySupported
Guid            : bbda27a4-0902-4a49-b634-4dc316b49812
Rules           :
StatelessReady  : True


Exporting the custom profile to an ISO...


Build complete!



PS C:\Users\David\Desktop\8>`

**Comment by heroes1412** [comment]
maybe, im using "Python 3.10.6". but i can create custom iso for 6.7 and 7.

**Comment by itiligent** [comment]
just becauase 6.7 works does not mean the later drivers for 8 follow the same sctructure. 6.7 is quaite different to 7 & 8. I keep a clean VM handy with all the prequisites installed ready to go. This assures a clean build every time.

**Comment by itiligent** [comment]
I also just re-ran with the very latest build of PowerCLI, it all works fine.
