### ISSUE TITLE
8.0 U3B

### ISSUE THREAD

**Issue by alsyundawy** [itiligent/ESXi-Custom-ISO#20]
2024-09-17 (Update 3b)

Imageprofile ESXi-8.0U3b-24280767-standard (Build 24280767)

**Comment by itiligent** [comment]
I wont have time to look at this for a while, but please feel free to edit the script and submit a PR, if you like.

**Comment by itiligent** [comment]
Actually the issue is very simple. VMware realeased  both 8.0U3b-24280767 & 8.0U3b-24262298 on the same day. I've simplified  the script's sort logic to handle this. 8.0U3b-2428076 is available now.
