### ISSUE TITLE
Add-EsxSoftwareDepot Command Fails to Connect

### ISSUE THREAD

**Issue by Messiah1977** [itiligent/ESXi-Custom-ISO#22]
I staged a clean Windows 10 VM and followed to instructions to install PowerCLI, Python, PIP, etc however when I try to run the script i receive the following error "Add-EsxSoftwareDepot failed to initialize....." (see print screen attached). I've tried using older versions of python and PowerCLI however the command will not execute. I also tried running the command manually however its still not working. Not sure if with all the Broadcom has made to ESXi is the command impacted? Any suggestions would be appreciated. Thank you.
![error](https://github.com/user-attachments/assets/bc2e5750-ec9b-4f69-a8c6-29305bb326f5)

**Comment by itiligent** [comment]
You didn't mention the esxi version you want to create so I canot offer much. For esxi6 you need to use the older powercli and install it offline and does not need python.  You must always start with a fresh machine as powercli does not uninstall fully

**Comment by Messiah1977** [comment]
my apologies i was trying with esxi 8 but also didn't work with esxi7 either. In addition i did start with a clean machine, i would revert to a clean state when i was trying different versions of python or powercli.

**Comment by itiligent** [comment]
maybe try  python 3.7.1 to  3.12. I am now getting python errors too

**Comment by itiligent** [comment]
FYI, Esxi 7 & 8 isos build fine with python 3.11.9 and latest powercli. I've updated the instructions
