### ISSUE TITLE
zimablade support

### ISSUE THREAD

**Issue by caejb** [itiligent/ESXi-Custom-ISO#23]
Hello, i tested it on zimablade and i get errors about vnics. Is it supported?

**Comment by itiligent** [comment]
actually could you do me a favour... I've added the 2.5gb drivers to the script. The ISO builds ok so if you could please create a new ISO with the updated script ant let me know how it goes with the Zimablade. I dont have one to test.

**Comment by caejb** [comment]
I will try it, thanks. Is the 6.7 the only build to run on zima hardware?

**Comment by itiligent** [comment]
With realtek NICs, ony esxi 6.7 is usable. Later versions of esxi removed vmkernel support and the only option is to go with a supported intel nic if you want esxi 7 or 8. FYI I've added the latest {restricted} 2024 update to the esxi build, so esxi 6.7 is still up to date in Oct 2024.

**Comment by caejb** [comment]
The installation was successful, but the adapter shows all time Disconnected. I dont think theres a 2.5GBte in the Zimablade, guess a 1Gbte too.

**Comment by itiligent** [comment]
ok, I suspect there are issues if both the 1gb and 2gb driver are in the image. 
Please try one more time but this time use the new script `esxi-zimamblade.ps1` I've just added. This will only add the 2.5gb driver

**Comment by caejb** [comment]
didnt worked.

**Comment by itiligent** [comment]
Thats interesting. What I know about zimblade is that unlike the zimaboard, the hardware on the device can vary. 

The only thing to do next is confirm the exact NIC device first. 

run `lspci` under esxi and post the output... assuming 6.7  has lspci  (esxi 7 & 8 do)

**Comment by caejb** [comment]
0000:00:00.0 Host bridge: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Host Bridge
0000:00:02.0 VGA compatible controller: Intel Corporation HD Graphics 500
0000:00:0e.0 Audio device: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster
0000:00:0f.0 Communication controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Trusted Execution Engine
0000:00:0f.1 Communication controller: Intel Corporation Device 5a9c
0000:00:0f.2 Communication controller: Intel Corporation Device 5a9e
0000:00:12.0 SATA controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series SATA AHCI Controller [vmhba0]
0000:00:13.0 PCI bridge: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series PCI Express Port A #1 [PCIe RP[0000:00:13.0]]
0000:00:14.0 PCI bridge: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series PCI Express Port B #1 [PCIe RP[0000:00:14.0]]
0000:00:14.1 PCI bridge: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series PCI Express Port B #2 [PCIe RP[0000:00:14.1]]
0000:00:15.0 USB controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series USB xHCI [vmhba32]
0000:00:16.0 Signal processing controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series I2C Controller #1
0000:00:16.2 Signal processing controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series I2C Controller #3
0000:00:1c.0 SD Host controller: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series eMMC Controller
0000:00:1f.0 ISA bridge: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series Low Pin Count Interface
0000:00:1f.1 SMBus: Intel Corporation Celeron N3350/Pentium N4200/Atom E3900 Series SMBus Controller
0000:02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168 PCI Express Gigabit Ethernet controller

**Comment by caejb** [comment]
The last one is my usb-c adapter ethernet port.

**Comment by itiligent** [comment]
This confirms the USBNIC fling works, and no NIC drivers are present.  What does lspci say when installing esxi with the standard 6.7 iso script? (wit just the 1gbe RTL NIC driver?)

A bettter way might be to also install a recent linux like ubuntu and run lspci - this should be able to support all devices and tell us exact hardware specifics present.

To make the usb adapter work see here configure https://github.com/itiligent/ESXi-Custom-ISO/blob/main/testlab-cheat-sheet.md#create-persistent-usb-nic-name-mappings

**Comment by caejb** [comment]
its an r8169.

**Comment by itiligent** [comment]
As I thought, the Zimaboard is diferent. 
The zimablade is a frankenstien product with several variations made very cheaply. Old hardware and  drivers are often a pain, especially as 8169 is a more obscure and cheaper 1gb NIC.
 
There might be a way to get this going by building esxi 6.5 instead, and then using the same script logic to add the only driver I know of. See here: https://vibsdepot.v-front.de/wiki/index.php/Net51-r8169

**Comment by itiligent** [comment]
I think I've solved it.  Look for a new script `esxi6.5-zimablade-only.ps1`.
 
The script will build an ISO with the latest 6.5 source (march 2024)  with RTL 8169 and INTEL NIC drivers. 

Note: 

- The USB and RTL 8168 drivers are commented out.  This is because both RTL drivers installed at once may cause the incorect drvier to load. (an issue with other rtl NIC and esxi)

- The USB NIC fling is giving xml errors on injection, I dont have time to troubleshoot - just manually add the extracted vib after install if USB NICs is needed.

Give the script a go and let me know.

**Comment by itiligent** [comment]
closing due to no response
