### ISSUE TITLE
Update section: 🛠️ Instructions for building ESXi ISOs: point 6

### ISSUE THREAD

**Issue by Blake64** [itiligent/ESXi-Custom-ISO#24]
Please correct point 6 of 🛠️ Instructions for building ESXi ISOs

`Set-PowerCLIConfiguration -PythonPath C:\Users\$env:USERNAME\AppData\Local\Programs\Python\Python37\python.exe`

should be 

`Set-PowerCLIConfiguration -PythonPath C:\Users\$env:USERNAME\AppData\Local\Programs\Python\Python311\python.exe`

or: 

`Set-PowerCLIConfiguration -PythonPath C:\Users\$env:USERNAME\AppData\Local\Programs\Python\Python<PYTHON_VERSION>\python.exe`

**Comment by itiligent** [comment]
Thanks for that. Done
